wagtail/contrib/settings/urls.py
from django.urls import path

from . import views

app_name = "wagtailsettings"
urlpatterns = [
    path("<slug:app_name>/<slug:model_name>/", views.edit_current_site, name="edit"),
    path("<slug:app_name>/<slug:model_name>/<int:site_pk>/", views.edit, name="edit"),
]

wagtail/contrib/settings/templates/wagtailsettings/edit.html
{% extends "wagtailadmin/base.html" %}
{% load i18n wagtailadmin_tags %}
{% block titletag %}{% blocktrans trimmed %}Editing {{ setting_type_name}} - {{ instance }}{% endblocktrans %}{% endblock %}
{% block bodyclass %}menu-settings{% endblock %}
{% block content %}
    <header class="header merged">
        <div class="row">
            <div class="left">
                <div class="col">
                    <h1 class="header__title">
                        {% icon name="cogs" %}
                        {% trans "Editing" %}
                        <span class="header__subtitle">{{ setting_type_name|capfirst }}</span>
                    </h1>
                </div>
            </div>
            <div class="right">
                {% if site_switcher %}
                    <div class="field choice_field">
                        <form method="get" class="setting-site-switch-form" id="settings-site-switch" novalidate>
                            <label for="{{ site_switcher.site.id_for_label }}">
                                {% trans "Site" %}:
                            </label>
                            <div class="input">
                                {{ site_switcher.site }}
                                <span></span>
                            </div>
                        </form>
                    </div>
                {% endif %}
            </div>
        </div>
    </header>

    <form action="{% url 'wagtailsettings:edit' opts.app_label opts.model_name site.pk %}" method="POST" novalidate{% if form.is_multipart %} enctype="multipart/form-data"{% endif %}>
        {% csrf_token %}
        {{ edit_handler.render_form_content }}

        <footer class="footer">
            <ul>
                <li class="actions dropdown dropup match-width footer__container">
                    <button type="submit" class="button button-longrunning" data-clicked-text="{% trans 'Saving…' %}">{% icon name="spinner" %}<em>{% trans 'Save' %}</em></button>
                </li>
            </ul>
        </footer>
    </form>

{% endblock %}

{% block extra_css %}
    {{ block.super }}
    {{ media.css }}
{% endblock %}
{% block extra_js %}
    {{ block.super }}
    {% include "wagtailadmin/pages/_editor_js.html" %}
    {{ media.js }}
{% endblock %}

wagtail/contrib/settings/templates/wagtailsettings/index.html
{% extends "wagtailadmin/base.html" %}
{% load i18n %}
{% block titletag %}{% trans "Settings" %}{% endblock %}
{% block bodyclass %}menu-settings{% endblock %}
{% block content %}

    {% include "wagtailadmin/shared/header.html" with title="Settings" icon="cogs" %}

    <div class="nice-padding">
        <ul class="listing">
            {% for name, description, content_type in setting_types %}
                <li>
                    <div class="row row-flush title">
                        <h2>
                            <a href="{% url 'wagtailsettings_edit' content_type.app_label content_type.model %}" class="col6">
                                {{ name|capfirst }}
                            </a>
                        </h2>
                        <small class="col6">{{ description }}</small>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}